config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  resources :users, :lesson
  resources :quizzes, only: [:index, :show]
  resources :entries, only: [:index, :create, :show]


end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end


end

app/views/quizzes/index.html.erb
<h1>Please select a quiz from below</h1>
<h4>Quiz 1 is the easiest, with each quiz increasing in difficulty</h4>

<div class = "row">
  <div class ="col-md-6 col-md-offset-3">

    <% @quizzes.all.each do |quiz| %>

    <h2><%= link_to quiz.name, quiz_path(quiz)%></h2>



    <% end %>

    </div>
</div>

app/views/quizzes/show.html.erb
<h1><%= @quiz.name %></h1>
<h4>Each correct answer is worth 2 points</h4>

<ul class="questions">

  <%= form_tag entries_path do %>
      <%= hidden_field_tag 'quiz_id' , @quiz.id%>
      <% @quiz.questions.each do |questions| %>
          <li>
            <%= questions.name %>
            <ul class="answers" %>
              <% questions.answers.each do |answer| %>
                  <li><%= radio_button_tag("answers[#{questions.id}]", answer.id) %>
                    <%= label(:answer, answer.name) %>
                  </li>
              <% end %>
            </ul>
          </li>
      <% end %>

      <%= submit_tag 'Complete' %>

  <% end %>


</ul>