config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  resources :users, :lesson
  resources :quizzes, only: [:index, :show]
  resources :entries, only: [:index, :create, :show]


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  level_id        :integer
#  score           :integer
#  last_login      :datetime
#

class User < ActiveRecord::Base

  belongs_to :level
  has_many :entries

  after_create :award_sign_up_bonus

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, length: {minimum: 6}


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def quiz_scores
    hash = {}
    Quiz.all.each do |q|
      hash["#{q.name}"] = Entry.where(quiz: q, user: id).maximum(:score)
    end
    hash
  end

  def award_sign_up_bonus
    update_attribute(:score, 10)
    update_attribute(:level_id, 1)
    update_attribute(:last_login, Time.now)
  end

  def award_login_bonus
    if last_login < 1.day.ago
      update_score_and_level(2)
      update_attribute(:last_login, Time.now)
      return 'Login Bonus - 2 points has been added to your score'
    end
    return ''
  end

  #Check entry and if it is the highest for that quiz, update score
  def new_entry(entry, highest_score)

    if Entry.where(quiz: entry.quiz, user: id).count == 1
      update_score_and_level(entry.score)
      return "Congrats, on your first time taking this quiz your score has increased by #{entry.score}"
    elsif entry.score >= highest_score
      diff = entry.score - highest_score
      update_score_and_level(diff)
      return "Congrats, you beat your last score, your score has increased by #{diff}"
    end
    return ""
  end


  def update_score_and_level(new_points)
    new_score = score + new_points
    update_attribute(:score, new_score)
    new_level = Level.find_level_for_score(new_score)
    if new_level && (!level || new_level.id > level_id)
      update_attribute(:level_id, new_level.id)
    end
  end


  def next_level
    next_levels = []
    Level.all.each do |level|
      next_levels << level unless level.id <= level_id
    end
    next_levels
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  # before_action :correct_user, only: [:show]

  def show
    @user = User.find(params[:id])
    @entries = @user.entries
  end

  def new
    @user = User.new
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Fun-Learning you have earned a 10 points signing up bonus!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_level.html.erb
<h2><%= "Level #{@user.level_id} - #{@user.level.name}" %></h2>

<% if @user.level_id == 1 %>
    <%= image_tag "level1.png", class: "img-responsive center-block" %>
<% elsif @user.level_id == 2 %>
    <%= image_tag "level2.png", class: "img-responsive center-block"  %>
<% elsif @user.level_id == 3 %>
    <%= image_tag "level3.png", class: "img-responsive center-block"  %>
<% elsif @user.level_id == 4 %>
    <%= image_tag "level4.png", class: "img-responsive center-block"  %>
<% end %>
<h4>Next Levels</h4>
<% @user.next_level.each do |level| %>
    <h4><%= "#{level.name} -- required score: #{level.required_score}" %></h4>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "Sign up") %>
<div class = "row">
<h1>Leaderboard</h1>
<h5>Click on any user to view  their profile.</h5>
</div>
<div class = "row">
  <div class ="col-md-6 col-md-offset-3">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Position</th>
        <th>Name</th>
        <th>Level</th>
        <th>Score</th>
      </tr>
      </thead>
      <tbody>
      <% i = 1 %>
      <% @user.sort_by{|u| u.score }.reverse.each do |u| %>
      <tr>
        <td><%= i %></td>
        <td><%= link_to "#{u.name}", user_path(u) %></td>
        <td><%= u.level_id %></td>
        <td><%= u.score  %></td>
      </tr>
          <% i += 1 %>
          <% end %>
          </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign Up</h1>

<div class = "row">
  <div class ="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control' %>


        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_cofirmation,"Confirmation" %>
        <%= f.password_field :password_cofirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn -primary" %>
        <% end %>

    </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="profile">
  <div class="row">
    <h2> <%= "#{@user.name}'s Profile " %> </h2>

    <div class="col-md-4">
      <section class="level">
        <%= render 'users/level' %>
      </section>
    </div>

    <div class="col-md-4">
      <section class="score">
        <h2>Score</h2>
        <h1><%= @user.score %></h1>
        <h4>Points</h4>
      </section>
    </div>

    <div class="col-md-4">
      <section class="high-scores">
        <h3>Highest Quiz Results</h3>
        <% @user.quiz_scores.each do |quiz_name, score| %>
            <h3><%= "#{quiz_name}: #{score}" %></h3>
        <% end %>
      </section>
    </div>

  </div>
  <div class="row">
    <div class="col-md-4">
        <p>Increase your level by getting a higher overall score!</p>
    </div>
    <div class="col-md-4">
        <p>Check out our <%= link_to "Leaderboard", users_path %> to see how your score ranks against others!</p>
      <h3>Once finished using our site could you please take our <a href="https://www.surveymonkey.com/s/YHVFHZ9 ">survey by following this link</a></h3>
    </div>
    <div class="col-md-4">
        <p>Not happy with your last result? Take a <%= link_to "Quiz", quizzes_path %> again to beat result and increase
          your overall score!</p>
    </div>
  </div>
</div>